description: Plan, Validate & Apply Terraform
examples:
  example:
    description: Plan and apply terraform after validating
    usage:
      orbs:
        terraform: sous-chefs/terraform@1
      version: 2.1
      workflows:
        terraform:
          jobs:
          - terraform/fmt
          - terraform/validate
          - terraform/plan:
              requires:
              - terraform/fmt
              - terraform/validate
          - terraform/apply:
              requires:
              - terraform/plan
executors:
  terraform:
    description: Hashicorp image without CircleCI convenience tools installed
    docker:
    - image: hashicorp/terraform
jobs:
  apply:
    environment:
      TF_WORKSPACE: <<parameters.workspace>>
    executor: terraform
    parameters:
      folder:
        default: .
        description: Folder to validate
        type: string
      workspace:
        default: default
        description: Terraform workspace name
        type: string
    steps:
    - checkout
    - run:
        command: terraform init -upgrade <<parameters.folder>>
        name: Initialize Terraform
    - run:
        command: terraform validate <<parameters.folder>>
        name: Validate Terraform
  fmt:
    executor: terraform
    steps:
    - checkout
    - run:
        command: terraform fmt -check -recursive
        name: Lint Terraform
  plan:
    environment:
      TF_WORKSPACE: <<parameters.workspace>>
    executor: terraform
    parameters:
      folder:
        default: .
        description: Folder to plan
        type: string
      workspace:
        default: default
        description: Terraform workspace name
        type: string
    steps:
    - checkout
    - run:
        command: terraform init -upgrade <<parameters.folder>>
        name: Initialize Terraform
    - run:
        command: terraform plan <<parameters.folder>>
        name: Plan Terraform
  validate:
    description: Validate terraform
    environment:
      TF_WORKSPACE: <<parameters.workspace>>
    executor: terraform
    parameters:
      folder:
        default: .
        description: Folder to validate
        type: string
      workspace:
        default: default
        description: Terraform workspace name
        type: string
    steps:
    - checkout
    - run:
        command: terraform init -upgrade <<parameters.folder>>
        name: Initialize Terraform
    - run:
        command: terraform validate <<parameters.folder>>
        name: Validate Terraform
version: 2.1

