---
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8

workflows:
  publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires: ["orb-tools/lint"]
      - orb-tools/publish-dev:
          orb-name: sous-chefs/terraform
          context: orb-publishing
          requires: [orb-tools/pack]
